-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 15:32:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Wholelink
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Wholelink
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Wholelink` DEFAULT CHARACTER SET utf8 ;
USE `Wholelink` ;

-- -----------------------------------------------------
-- Table `Wholelink`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`User` (
  `Username` VARCHAR(20) NULL,
  `User_id` INT NOT NULL,
  `Password` VARCHAR(32) NULL,
  `E-mail_Address` VARCHAR(32) NULL,
  `User_Agreement` TINYINT NULL,
  `Phone_Number` INT NULL,
  `Data_Of_Birth` DATE NULL,
  `Register_Time` DATETIME NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Home` (
  `House_id` INT NULL,
  `Address` VARCHAR(45) NULL,
  `House_Name` VARCHAR(45) NULL,
  `Room_Number` INT NOT NULL,
  `User_User_id` INT NOT NULL,
  PRIMARY KEY (`Room_Number`),
  INDEX `fk_Home_User1_idx` (`User_User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Home_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `Wholelink`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Rooms` (
  `Room_Name` INT NULL,
  `Number_Of_Devices` VARCHAR(45) NULL,
  `Room number` INT NOT NULL,
  `Home_Room_Number` INT NOT NULL,
  INDEX `fk_Rooms_Home1_idx` (`Home_Room_Number` ASC) VISIBLE,
  PRIMARY KEY (`Room number`),
  CONSTRAINT `fk_Rooms_Home1`
    FOREIGN KEY (`Home_Room_Number`)
    REFERENCES `Wholelink`.`Home` (`Room_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Devices` (
  `Device_id` INT NOT NULL,
  `Device_Name` VARCHAR(45) NULL,
  `Device_Type` VARCHAR(45) NOT NULL,
  `User_User_id` INT NULL,
  `User_User_id1` INT NOT NULL,
  `Rooms_Room number` INT NOT NULL,
  `Device_Status` TINYINT NULL,
  `Color` VARCHAR(45) NULL,
  `Brightness` FLOAT NULL,
  `Modes` VARCHAR(45) NULL,
  `Schedule` DATETIME NULL,
  PRIMARY KEY (`Device_id`, `Device_Type`),
  INDEX `fk_Devices_User1_idx` (`User_User_id1` ASC) VISIBLE,
  INDEX `fk_Devices_Rooms1_idx` (`Rooms_Room number` ASC) VISIBLE,
  CONSTRAINT `fk_Devices_User1`
    FOREIGN KEY (`User_User_id1`)
    REFERENCES `Wholelink`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devices_Rooms1`
    FOREIGN KEY (`Rooms_Room number`)
    REFERENCES `Wholelink`.`Rooms` (`Room number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Admin` (
  `Username` VARCHAR(32) NOT NULL,
  `Password` VARCHAR(32) NULL,
  `Admin_id` INT NULL,
  `Level` TINYINT(4) NULL,
  `Create_Time` DATETIME NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Device Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Device Status` (
  `Device_Type` VARCHAR(45) NULL,
  `Device_Status` TINYINT(5) NULL,
  `Devices_User_User_id` INT NOT NULL,
  `Devices_Device_id` INT NOT NULL,
  `Devices_Device_id1` INT NOT NULL,
  PRIMARY KEY (`Devices_User_User_id`, `Devices_Device_id`),
  INDEX `fk_Device Status_Devices1_idx` (`Devices_Device_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Device Status_Devices1`
    FOREIGN KEY (`Devices_Device_id1`)
    REFERENCES `Wholelink`.`Devices` (`Device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Log` (
  `Event_Time` DATETIME NOT NULL,
  PRIMARY KEY (`Event_Time`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Commands` (
  `Command_id` INT NOT NULL,
  `Command_Text` VARCHAR(1000) NULL,
  PRIMARY KEY (`Command_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Functions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Functions` (
  `Avalable` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`User_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`User_has_User` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Messages` (
  `Messages` VARCHAR(1000) NOT NULL,
  `User_User_id` INT NOT NULL,
  `Admin_Username` VARCHAR(32) NOT NULL,
  INDEX `fk_Messages_User1_idx` (`User_User_id` ASC) VISIBLE,
  PRIMARY KEY (`Messages`),
  INDEX `fk_Messages_Admin1_idx` (`Admin_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `Wholelink`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Admin1`
    FOREIGN KEY (`Admin_Username`)
    REFERENCES `Wholelink`.`Admin` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Rooms_has_Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Rooms_has_Devices` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Device Status_has_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Device Status_has_Log` (
  `Device Status_Devices_User_User_id` INT NOT NULL,
  `Device Status_Devices_Device_id` INT NOT NULL,
  PRIMARY KEY (`Device Status_Devices_User_User_id`, `Device Status_Devices_Device_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Data for Ai_has_Device Status_has_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Data for Ai_has_Device Status_has_Log` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Device Status_has_Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Device Status_has_Logs` (
  `Device Status_Devices_User_User_id` INT NOT NULL,
  `Device Status_Devices_Device_id` INT NOT NULL,
  `Log_Event_Time` DATETIME NOT NULL,
  PRIMARY KEY (`Device Status_Devices_User_User_id`, `Device Status_Devices_Device_id`, `Log_Event_Time`),
  INDEX `fk_Device Status_has_Log1_Log1_idx` (`Log_Event_Time` ASC) VISIBLE,
  INDEX `fk_Device Status_has_Log1_Device Status1_idx` (`Device Status_Devices_User_User_id` ASC, `Device Status_Devices_Device_id` ASC) VISIBLE,
  CONSTRAINT `fk_Device Status_has_Log1_Device Status1`
    FOREIGN KEY (`Device Status_Devices_User_User_id` , `Device Status_Devices_Device_id`)
    REFERENCES `Wholelink`.`Device Status` (`Devices_User_User_id` , `Devices_Device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Device Status_has_Log1_Log1`
    FOREIGN KEY (`Log_Event_Time`)
    REFERENCES `Wholelink`.`Log` (`Event_Time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`` (
  `Rooms_Room number` INT NOT NULL,
  `Devices_Device_id` INT NOT NULL,
  PRIMARY KEY (`Rooms_Room number`, `Devices_Device_id`),
  INDEX `fk_Rooms_has_Devices1_Devices1_idx` (`Devices_Device_id` ASC) VISIBLE,
  INDEX `fk_Rooms_has_Devices1_Rooms1_idx` (`Rooms_Room number` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_has_Devices1_Rooms1`
    FOREIGN KEY (`Rooms_Room number`)
    REFERENCES `Wholelink`.`Rooms` (`Room number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rooms_has_Devices1_Devices1`
    FOREIGN KEY (`Devices_Device_id`)
    REFERENCES `Wholelink`.`Devices` (`Device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wholelink`.`Devices Functions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`Devices Functions` (
  `Functions` VARCHAR(100) NOT NULL,
  `Devices_Device_id` INT NOT NULL,
  `Devices_Device_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Functions`),
  INDEX `fk_Devices Functions_Devices1_idx` (`Devices_Device_id` ASC, `Devices_Device_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Devices Functions_Devices1`
    FOREIGN KEY (`Devices_Device_id` , `Devices_Device_Type`)
    REFERENCES `Wholelink`.`Devices` (`Device_id` , `Device_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Wholelink` ;

-- -----------------------------------------------------
-- Placeholder table for view `Wholelink`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wholelink`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Wholelink`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wholelink`.`view1`;
USE `Wholelink`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
